### ISSUE TITLE
Remove this class, use Nurse as class to move nurse data

### ISSUE THREAD

**Issue by Japoivvb** [vctrgz/hospital_backend#15]
https://github.com/vctrgz/hospital_backend/blob/e7e17983da61257403a803a63d4198aa41758ee3/src/main/java/SpringBoot/Hospital/LoginRequest.java#L3C14-L3C27

**Comment by vctrgz** [comment]
Crear constructor en Nurse y utilizar Nurse nurse en input en vez de LoginRequest loginRequest?
